# render.yaml - drop at repo root
services:
  - name: digital-wallet-frontend
    type: web
    env: docker
    branch: main
    repo: https://github.com/AbbeyMathew/digital-wallet
    root: frontend
    dockerfilePath: Dockerfile
    plan: free
    startCommand: "npm run dev" 
    envVars:
      - key: PORT
        value: "5173"

  - name: digital-wallet-backend
    type: web
    env: docker
    branch: main
    repo: https://github.com/AbbeyMathew/digital-wallet
    root: backend
    dockerfilePath: Dockerfile
    plan: free
    startCommand: "npm run dev"
    envVars:
      - key: PORT
        value: "5000"
