services:
  - name: digital-wallet-frontend
    type: web
    env: docker
    repo: https://github.com/AbbeyMathew/digital-wallet
    branch: main
    dockerfilePath: frontend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "5173"

  - name: digital-wallet-backend
    type: web
    env: docker
    repo: https://github.com/AbbeyMathew/digital-wallet
    branch: main
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "5000"
